services:
  selenium:
    image: selenium/standalone-firefox
    expose:
      - "4444"
      - "4317"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 10s
    environment:
      - SE_ENABLE_TRACING=false

  python-app:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      - SELENIUM_HOST=selenium
      - FLASK_APP=weedTracker.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - .:/code
    restart: unless-stopped